CREATE TABLE DEMO.CONFIGURATION_PARAMETERS(
	ID serial PRIMARY KEY,
	FUN VARCHAR (50) NOT NULL,
	COD VARCHAR (50) NOT NULL,
	VALUE VARCHAR (50) NOT NULL,
	DESCRIPTION VARCHAR (355),
	created_on TIMESTAMP NOT NULL
);